REM # --------------------- #
REM # (C) 2022 madoodia.com #
REM # --------------------- #

@echo OFF

@REM set ROOT=%~dp0

REM SDKS_LOCATION
@REM set SDKS_LOCATION=D:/madoodia/sdks

REM GLEW_LOCATION
@REM set GLEW_LOCATION=%SDKS_LOCATION%/OpenGL/GLEW

REM GLFW_LOCATION
@REM set GLFW3_ROOT=%SDKS_LOCATION%/OpenGL/GLFW
@REM set GLFW3_INCLUDE_DIR=%SDKS_LOCATION%/OpenGL/GLFW/include
@REM set GLFW3_LIBRARIES=%SDKS_LOCATION%/OpenGL/GLFW/lib

REM GLM_LOCATION
@REM set GLM_ROOT_DIR=%SDKS_LOCATION%/OpenGL/GLM

REM GLAD_LOCATION
@REM set GLAD_INCLUDE_DIR=%SDKS_LOCATION%/OpenGL/GLAD/include

REM GLEW_LOCATION
@REM set GLEW_LOCATION=%SDKS_LOCATION%/OpenGL/GLEW
@REM set GLEW_INCLUDE_DIRS=%SDKS_LOCATION%/OpenGL/GLEW/include
@REM set GLEW_LIBRARIES=%SDKS_LOCATION%/OpenGL/GLEW/lib

REM ASSIMP_LOCATION
@REM set ASSIMP_INCLUDE_DIR=%SDKS_LOCATION%/OpenGL/ASSIMP/include
@REM set ASSIMP_LIBRARIES=%SDKS_LOCATION%/OpenGL/ASSIMP/lib

@REM CMAKE_MODULE_PATH
@REM set CMAKE_MODULE_PATH=%ROOT%/cmake/modules

REM STB_LOCATION
@REM set STB_LOCATION=%SDKS_LOCATION%/OpenGL/STB